USE [TH_AD]
GO

/****** Object:  StoredProcedure [dbo].[AMPLIACIONLICMED]    Script Date: 02/25/2019 15:50:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--AMPLIACIÓN
CREATE PROCEDURE [dbo].[AMPLIACIONLICMED]
AS
--INICIO PROCEDIMIENTO ALMACENADO
;WITH N(N) AS 
	(
	--SELECCIÓN DE TODAS LAS COLUMNAS DEL SISTEMA
	SELECT ROW_NUMBER() OVER (ORDER BY [object_id])-1 FROM SYS.ALL_COLUMNS
	),
	--DEFINICIÓN DE COLUMNAS PARA REALIZAR AMPLIACIÓN
	D(N,F,T,MD,BP,EP,
	--COLUMNAS TABLA ORIGINAL HISTORICOLICMED
	VALIDO,IDHIST,ID_HR,TIPO,ID_TIPO,NOM_INC,RUT,NOMBRE,ID_EMP,NOM_POS,DIAS_DURAC,INI,FIN,NUM_LIC,ID_USU_ACT,ULT_ACT) AS  
	(
		SELECT n.N,d.INI,d.FIN,
			--AMPLIACIÓN DE PERIODOS, CORTE DE INI HASTA FIN DE MES (DATEADD)
			DATEDIFF(MONTH, d.INI, d.FIN),
			DATEADD(MONTH, n.N, DATEADD(DAY, 1-DAY(INI), INI)),
			DATEADD(DAY, -1, DATEADD(MONTH, 1, DATEADD(MONTH, n.N, 
			DATEADD(DAY, 1-DAY(INI), INI)))),
			--COLUMNAS TABLA ORIGINAL
			D.VALIDO,D.IDHIST,D.ID_HR,D.TIPO,D.ID_TIPO,D.NOM_INC,D.RUT,D.NOMBRE,D.ID_EMP,D.NOM_POS,D.DIAS_DURAC,D.INI,D.FIN,D.NUM_LIC,D.ID_USU_ACT,D.ULT_ACT
		FROM N INNER JOIN HISTORICOLICMED AS D
		--CÁLCULO CORTE FIN DE MES
		ON d.FIN >= DATEADD(MONTH, n.N-1, d.INI)
	), E AS (
		SELECT VALIDO,IDHIST,ID_HR,TIPO,ID_TIPO,NOM_INC,RUT,NOMBRE,ID_EMP,NOM_POS,INI,FIN,NUM_LIC,ID_USU_ACT,ULT_ACT, --dias_durac
		--MANTENER COLUMNAS ORIGINALES INI / FIN
		CONVERT(NVARCHAR(10),F, 103) as original_INI, CONVERT(NVARCHAR(10),t, 103) as original_FIN, DIAS_DURAC,
		--COLUMNAS CON AMPLIACIÓN, SE CONVIERTEN FECHAS PARA FACILIDAD DE MANIPULACIÓN
		CONVERT(NVARCHAR(10), CASE n WHEN 0 THEN f ELSE bp END,103) AS nuevo_INI,
		--new_INI = CASE n WHEN 0 THEN f ELSE bp END,
		CONVERT(NVARCHAR(10), CASE n WHEN md THEN t ELSE ep END,103) AS nuevo_FIN
		--new_INI = CASE n WHEN md THEN t ELSE bp END
		FROM D
		WHERE MD >= N
	), I AS (
		--SELECCIÓN DE ELEMENTOS DE LA TABLA E Y CÁLCULO DE LA DIFERENCIA DE DÍAS
		SELECT E.*, 
				DATEDIFF(DD, NUEVO_INI,NUEVO_FIN)+1 as DIAS_DURAC2, 
				CONVERT(nvarchar(6),CAST(nuevo_ini as datetime),112) as PERPRO
		FROM E --ORDER BY IDHIST 
	)
	--INSERCIÓN DE DATOS DE TABLA I EN HISTORICOLICMEDPROC
	INSERT INTO DBO.HISTORICOLICMEDPROC 
	(VALIDO,IDHIST,ID_HR,TIPO,ID_TIPO,NOM_INC,RUT,NOMBRE,ID_EMP,NOM_POS,INI,FIN,NUM_LIC,ID_USU_ACT,ULT_ACT,ORIGINAL_INI,ORIGINAL_FIN,DIAS_DURAC,NUEVO_INI,NUEVO_FIN,DIAS_DURAC2,PERPRO)
	SELECT I.VALIDO,I.IDHIST,I.ID_HR,I.TIPO,I.ID_TIPO,I.NOM_INC,I.RUT,I.NOMBRE,I.ID_EMP,I.NOM_POS,I.INI,I.FIN,I.NUM_LIC,I.ID_USU_ACT,
		I.ULT_ACT,I.ORIGINAL_INI,I.ORIGINAL_FIN,I.DIAS_DURAC,I.NUEVO_INI,I.NUEVO_FIN,I.DIAS_DURAC2,I.PERPRO
	FROM I 
	--SE INSERTA EN TABLA_Y DONDE LA FECHA DE ACTUALIZACIÓN MÁXIMA DE LA TABLA_X SEA MAYOR AL DE LA TABLA_Y
	WHERE ULT_ACT > (SELECT MAX(ULT_ACT) FROM HISTORICOLICMEDPROC)
	--WHERE I.ULT_ACT BETWEEN (SELECT MAX(ULT_ACT) FROM HISTORICOLICMEDPROC) AND (SELECT MAX(ULT_ACT) FROM HISTORICOLICMED)
	--	AND I.ULT_ACT <> (SELECT MAX(ULT_ACT) FROM HISTORICOLICMED)

	--WHERE NOT EXISTS (SELECT 1 FROM historicoLicMedProc T2
	--						WHERE T.ID_HR = T2.ID_HR AND
	--							T.INI = T2.INI)
	
	--POR REQUERIMIENTO SE ELIMINAN PERIODOS POSTERIORES AL 01/01/2012 Y ACTUALIZADOS POSTERIORES AL 01/11/2011
	DELETE FROM HISTORICOLICMEDPROC WHERE PERPRO < 201201 AND ULT_ACT < '01/11/2011';

GO


