USE [TH_AD]
GO

/****** Object:  StoredProcedure [dbo].[AMPLIACIONVAC]    Script Date: 02/25/2019 15:51:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[AMPLIACIONVAC]
AS

;WITH N(N) AS 
	(
	SELECT ROW_NUMBER() OVER (ORDER BY [object_id])-1 FROM SYS.ALL_COLUMNS
	),
	D(N,F,T,MD,BP,EP,
	--COLUMNAS TABLA ORIGINAL HISTORICOVAC
	VALIDO,IDHIST,ID_HR,RUT,NOMBRE,MARCA,ID_TIP,NOM_POS,NOM_INC,INI,FIN,DIAS_DUR,SUBIDO) AS  
	(
		SELECT n.N,d.INI,d.FIN,
			DATEDIFF(MONTH, d.INI, d.FIN),
			DATEADD(MONTH, n.N, DATEADD(DAY, 1-DAY(INI), INI)),
			DATEADD(DAY, -1, DATEADD(MONTH, 1, DATEADD(MONTH, n.N, 
			DATEADD(DAY, 1-DAY(INI), INI)))),
			--COLUMNAS TABLA ORIGINAL
			D.VALIDO,D.IDHIST,D.ID_HR,D.RUT,D.NOMBRE,D.MARCA,D.ID_TIP,D.NOM_POS,D.NOM_INC,D.INI,D.FIN,D.DIAS_DUR,D.SUBIDO
		FROM N INNER JOIN HISTORICOVAC AS D
		ON d.FIN >= DATEADD(MONTH, n.N-1, d.INI)
	), E AS (
		SELECT VALIDO,IDHIST,ID_HR,RUT,NOMBRE,MARCA,ID_TIP,NOM_POS,NOM_INC,INI,FIN,SUBIDO, --dias_durac
		--columnas originales INI / FIN
		CONVERT(NVARCHAR(10),F, 103) as original_INI, CONVERT(NVARCHAR(10),t, 103) as original_FIN, DIAS_DUR,
		--columnas con ampliación
		CONVERT(NVARCHAR(10), CASE n WHEN 0 THEN f ELSE bp END,103) AS nuevo_INI,
		--new_INI = CASE n WHEN 0 THEN f ELSE bp END,
		CONVERT(NVARCHAR(10), CASE n WHEN md THEN t ELSE ep END,103) AS nuevo_FIN
		--new_INI = CASE n WHEN md THEN t ELSE bp END
		FROM D
		WHERE MD >= N
	), I AS (
		SELECT E.*, 
				(
					SELECT COUNT(CONVERT(INT,feriadoBancario,112)) AS D
					FROM CALENDAR C
					WHERE feriadoBancario=0 AND 
						C.fechaValor BETWEEN NUEVO_INI AND NUEVO_FIN
				) AS DIAS_DUR2,
				CONVERT(nvarchar(6),CAST(nuevo_ini as datetime),112) as PERPRO
		FROM E --ORDER BY IDHIST 
	)
	
	INSERT INTO DBO.HISTORICOVACPROC 
	(VALIDO,IDHIST,ID_HR,RUT,NOMBRE,MARCA,NOM_POS,ID_TIP,NOM_INC,INI,FIN,DIAS_DUR,SUBIDO,ORIGINAL_INI,ORIGINAL_FIN,NUEVO_INI,NUEVO_FIN,DIAS_DUR2,PERPRO)
	SELECT I.VALIDO,I.IDHIST,I.ID_HR,I.RUT,I.NOMBRE,I.MARCA,I.NOM_POS,ID_TIP,I.NOM_INC,I.INI,I.FIN,I.DIAS_DUR,I.SUBIDO,
		I.ORIGINAL_INI,I.ORIGINAL_FIN,I.NUEVO_INI,I.NUEVO_FIN,I.DIAS_DUR2,I.PERPRO
	FROM I 
	--WHERE SUBIDO > (SELECT MAX(SUBIDO) FROM HISTORICOVACPROC) OR (SELECT MAX(SUBIDO) FROM HISTORICOVACPROC) = NULL

	--DBCC CHECKINDENT ('HISVACPROC',RESEED,0)
	--WHERE NOT EXISTS(SELECT * FROM HISTORICOVACPROC TH WHERE TH.IDHIST = TH.IDHIST)
	
	DELETE FROM HISTORICOVACPROC WHERE PERPRO < 201201 OR SUBIDO < '01/11/2011';
	

GO


