USE [TH_AD]
GO

/****** Object:  StoredProcedure [dbo].[VALIDASOLAPLIC]    Script Date: 02/25/2019 15:51:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[VALIDASOLAPLIC]
AS 
;WITH CTE AS
(
	SELECT ROW_NUMBER() OVER (PARTITION BY ID_HR ORDER BY ULT_ACT ASC) AS IDOR,
	T.VALIDO,
	--T.ID,
	T.RUT,
	T.ID_HR,
	CONVERT(VARCHAR, T.INI, 112) AS INI,
	CONVERT(VARCHAR, T.FIN, 112) AS FIN,
	CONVERT(VARCHAR, T.ULT_ACT, 112) AS ULT_ACT
	FROM HISTORICOLICMEDPROC T
		WHERE EXISTS
			(
				SELECT 1 FROM HISTORICOLICMEDPROC T2 
					WHERE T.RUT = T2.RUT AND
						T.IDHIST <> T2.IDHIST AND
						T.ULT_ACT <> T2.ULT_ACT AND
						--T2.INI <= T.FIN
						(T2.INI BETWEEN T.INI AND T.FIN)-- OR
						--T2.INI = T.FIN
						
					--(T2.INI BETWEEN T.INI AND T.FIN) OR
					--T2.INI = T.FIN
			)
)
	SELECT * FROM TSTSOLAP
--UPDATE CTE SET VALIDO = 0
--GO

--UPDATE T SET VALIDO = 0 --,T.FIN = (T2.INI - 1),
--FROM HISTORICOLICMED T
--INNER JOIN HISTORICOLICMED T2 ON
--T.RUT = T2.RUT 
--WHERE
--	T.ID <> T2.ID AND
--	T2.INI BETWEEN T.INI AND T.FIN OR
--	T2.INI = T.FIN
	
	--(T2.INI BETWEEN T.INI AND T.FIN) OR
	--T2.INI = T.FIN
-------------------------------------

GO


